version: '2'
services:
  web:
    container_name: web
    build: docker/nginx
    ports:
      - 3000:80
    links:
      - node
    volumes:
      - ./app:/var/www/html
  node:
    build: ./docker/node
    container_name: node
    hostname: node
    volumes:
    - ./app:/var/www/html
    working_dir: /var/www/html
    links:
      - mysql
  mysql:
    container_name: mysql
    build: docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=express
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 3001:80
    volumes:
     - /sessions
